### ISSUE TITLE
Wrong content type blocks CSS

### ISSUE THREAD

**Issue by rbzn** [clabs/rockon#25]
While running the server locally, the CSS will not be loaded, as the static webserver always returns `text/html` as the content type. This might work with images, but CSS will be blocked as the additional header `X-Content-Type-Options: nosniff` is als present.

[Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options)

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/1914746/212491497-1e39b00d-69b5-468c-8d03-8b42d3988985.png">

**Comment by ethrgeist** [comment]
Django needs to be in debug=True to deliver static files, set via .env file.
